### ISSUE TITLE
Refactor AET03 and AET04 layouts to work with trim_levels_in_group

### ISSUE THREAD

**Issue by anajens** [insightsengineering/tern#120]
For `AET04` and `AET03` layouts, please use the split function `trim_levels_in_group` instead of `drop_split_levels`. This is applicable only to layouts where we don't want to "fill in" rows with 0s for combinations of grades and events not observed in the analysis data.

This function will trim based on the empirical map. More background here: https://github.com/Roche/rtables/issues/236

Rationale: improved speed. 

Example of layout which is currently working:
```r
basic_table() %>%
  split_rows_by("AEBODSYS", split_fun = trim_levels_in_group("AETOXGR"), child_labels = "visible") %>%
  summarize_occurrences_by_grade(var = "AETOXGR") %>%
  split_rows_by("AEDECOD", split_fun = trim_levels_in_group("AETOXGR")) %>%
  count_occurrences_by_grade(var = "AETOXGR") %>%
  build_table(adae, alt_counts_df = adsl)
```

What needs to be refactored: helper function `h_append_grade_groups` is currently too strict when grade_groups are not found in the reference. This happens now because grades are dropped based on the split funciton.

Please add links to PRs below.
- [x] tern design doc for changes to `h_append_grade_groups` and possibly `s_count_occurrences_by_grade` #220 
- [x] tern production code carrying out design doc above. Also update relevant unit tests. #229 
- [x] teal.modules.clinical update. Note: Modules should aways split on the empirical map (observed combinations in the data) to make processing fast. insightsengineering/teal.modules.clinical#193
- [x] TLG-C update https://code.roche.com/nest/docs/tlg-catalog/devel/-/merge_requests/37
- [x] nsdl.tests update https://code.roche.com/nest/nsdl.tests/-/merge_requests/19

Example usage of full layout should look like this:

```r
gr_grp <-  list(
  "- Any Grade -" = c("1", "2", "3", "4", "5"),
  "Grade 1-2" = c("1", "2"),
  "Grade 3-4" = c("3", "4"),
  "Grade 5" = "5"
)

  lyt <- basic_table() %>%
    split_cols_by("ACTARM") %>%
    add_colcounts() %>%
    summarize_occurrences_by_grade(
      var = "AETOXGR",
      grade_groups = gr_grp
    ) %>%
    split_rows_by(
      "AEBODSYS", 
      child_labels = "visible", 
      nested = TRUE, 
      indent_mod = -1L,
      split_fun = trim_levels_in_group("AETOXGR"), # change here
      label_pos = "topleft",
      split_label = obj_label(adae$AEBODSYS)
    ) %>%
    summarize_occurrences_by_grade(
      var = "AETOXGR",
      grade_groups = gr_grp
    ) %>%
    split_rows_by(
      "AEDECOD", 
      child_labels = "visible", 
      nested = TRUE, 
      indent_mod = -1L,
      split_fun = trim_levels_in_group("AETOXGR"), # change here
      label_pos = "topleft",
      split_label = obj_label(adae$AEDECOD)
    ) %>%
    summarize_num_patients(
      var = "USUBJID",
      .stats = "unique",
      .labels = "- Any Grade -"
    ) %>%
    count_occurrences_by_grade(
      var = "AETOXGR",
      grade_groups = gr_grp[-1],
      .indent_mods = -1L
    ) %>%
    append_varlabels(adae, "AETOXGR", indent = 2L)

# Note removed  trim_rows() as it's no longer necessary.
result <- lyt %>%
  build_table(adae, alt_counts_df = adsl) %>%
  sort_at_path(
    path = "AEBODSYS",
    scorefun = cont_n_allcols,
    decreasing = TRUE
  ) %>%
  sort_at_path(
    path = c("AEBODSYS", "*", "AEDECOD"),
    scorefun = cont_n_allcols,
    decreasing = TRUE
  )

result
```
