### ISSUE TITLE
Splitting mmrm from tern -- Depreciate function calls

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#415]
# Motivation

In tern.mmrm

```
The following objects are masked from ‘package:tern’:

    a_mmrm_lsmeans, a_mmrm_lsmeans_single, fit_mmrm, g_mmrm_diagnostic, g_mmrm_lsmeans, h_mmrm_cov,
    h_mmrm_diagnostic, h_mmrm_fixed, s_mmrm_lsmeans, s_mmrm_lsmeans_single, summarize_lsmeans

```

# TODO

Depreciate function calls in the following files.

- [ ] [fit_mmrm.R](https://github.com/insightsengineering/tern/blob/main/R/fit_mmrm.R)
- [ ] [g_mmrm.R](https://github.com/insightsengineering/tern/blob/main/R/g_mmrm.R)
- [ ] [tabulate_mmrm.R](https://github.com/insightsengineering/tern/blob/main/R/tabulate_mmrm.R)
