### ISSUE TITLE
[UAT] manually run and test example code in `R/coxph.R`

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#452]
# Motivation
`rtables` and `formatable` packages are taking care of var_labels from upstream. Some potential break changes in the example code

# ToDo

- [x] Manually run and test example code
- [x] If the example code fails, create a *BUG* reporting issue in tern with title "[UAT] example code fails in `R/coxph.R` "
- [x] If multiple errors, create multiple issues
- [x] If issues created, reference in the comment

# Definition of done

* test example code works
* BUG reporting issues reference created if testing example code fails
