### ISSUE TITLE
Description function d_pkparam for PK parameter map for sorting

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#474]
# Motivation

From UAT comment, PK parameter needs to be sorted (https://github.com/insightsengineering/sme-tasks/issues/108#issuecomment-1022562478)

# TODO

- [x] create description function d_pkparam(), return data.frame of pk parameter data.frame
- [x] Hard code "Appendix 1: Parameter Labels for TLGs and Ordering:" from https://docs.google.com/file/d/1fUiyNYP17LFCHa6SSHymkDd0IL0r4oAT/view to data.frame
- [x] add documentation
- [x] update NEWS.md

# Definition of done

d_pkparam function
