### ISSUE TITLE
Create summarize_glm_count.R from RATET01 design doc

### ISSUE THREAD

**Issue by brandondbutcher** [insightsengineering/tern#538]
# Motivation

This is part of adding the new template RATET01, see https://github.com/insightsengineering/tern/issues/319

# To-Do:

## Pull code out of design doc (tern/design/design_ratet01.Rmd) and put into separate file, summarize_glm_count.R
- [x] Helper functions: h_glm_quasipoisson, h_glm_poisson, h_glm_ppmeans, & h_glm_count
- [x] Statistics function: s_glm_count
- [x] Analysis function: a_glm_count
- [x] Summarize function: summarize_glm_count 
- [x] Add annotations in summarize_glm_count.R for documentation. See summarize_ancova.R for examples.
- [ ] Create unit tests

DO NOT include h_glm_negbin helper function for the first iteration of this implementation.
