### ISSUE TITLE
create test file `test-table_pkpt03_05_07.R`

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#555]
# TODO

- [x] rename testile `test-table_pkpt03.R` to `test-table_pkpt03_05_07.R`
- [x] Adding tests for `pkpt05` (with urine data)
- [x] Adding tests for `pkpt07` (with noralized dose data)
