### ISSUE TITLE
fix break changes due to upstream changes in formatters of "na_str"

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#687]
# Motivation 

```
  ── Failure (test-response_subgroups.R:377:3): tabulate_rsp_subgroups functions as expected when 0 obs in one arm ──
  `result_matrix` not equal to `expected_matrix`.
  2/81 mismatches
  x[54]: "NA"
  y[54]: "NA%"
  
  x[72]: "NA"
  y[72]: "(NA, NA)"
  ── Failure (test-summarize_variables.R:420:3): create_afun_summary creates an `afun` that works ──
  `result_matrix` not identical to `expected_matrix`.
  9/136 mismatches
  x[75]: "NA"
  y[75]: "(NA, NA)"
  
  x[86]: "NA"
  y[86]: "(NA, NA)"
  
  x[97]: "NA"
  y[97]: "(NA, NA)"
  
  x[108]: "NA"
  y[108]: "NA - NA"
  
  x[109]: "NA"
  y[109]: "(NA, NA)"
  ── Failure (test-summarize_variables.R:478:3): `summarize_vars` works with healthy input, alternative `na.rm = FALSE` ──
  to_string_matrix(result) not identical to `expected`.
  2/10 mismatches
  x[8]: "NA"
  y[8]: "NA (NA)"
  
  x[10]: "NA"
  y[10]: "NA - NA"
  ── Failure (test-summarize_variables.R:641:3): `summarize_vars` works with empty named numeric variables ──
  `result_matrix` not identical to `expected_matrix`.
  2/20 mismatches
  x[8]: "NA"
  y[8]: "NA (NA)"
  
  x[10]: "NA"
  y[10]: "NA - NA"
  ── Failure (test-survival_duration_subgroups.R:435:3): tabulate_survival_subgroups functions as expected when one arm has 0 records ──
  `result_matrix` not equal to `expected_matrix`.
  2/110 mismatches
  x[99]: "NA"
  y[99]: "(NA, NA)"
  
  x[100]: "NA"
  y[100]: "(NA, NA)"
  ── Failure (test-table_egt01.R:80:3): EGT01 default variant is produced correctly ──
  `result_matrix` not identical to `expected_matrix`.
  6/294 mismatches
  x[89]: "NA"
  y[89]: "NA (NA)"
  
  x[91]: "NA"
  y[91]: "NA - NA"
  
  x[173]: "NA"
  y[173]: "NA (NA)"
  
  x[175]: "NA"
  y[175]: "NA - NA"
  
  x[257]: "NA"
  y[257]: "NA (NA)"
  ── Failure (test-table_lbt01.R:66:3): LBT01 default variant is produced correctly ──
  `result_matrix` not identical to `expected_matrix`.
  4/224 mismatches
  x[106]: "NA"
  y[106]: "NA (NA)"
  
  x[108]: "NA"
  y[108]: "NA - NA"
  
  x[138]: "NA"
  y[138]: "NA (NA)"
  
  x[140]: "NA"
  y[140]: "NA - NA"
  ── Failure (test-table_vst01.R:129:3): VST01 default variant is produced correctly ──
  `result_matrix` not identical to `expected_matrix`.
  6/371 mismatches
  x[112]: "NA"
  y[112]: "NA (NA)"
  
  x[114]: "NA"
  y[114]: "NA - NA"
  
  x[218]: "NA"
  y[218]: "NA (NA)"
  
  x[220]: "NA"
  y[220]: "NA - NA"
  
  x[324]: "NA"
  y[324]: "NA (NA)"
```

# TODO 

Fix test cases in 

- [x] test-response_subgroups.R
- [x] test-summarize_variables.R
- [x] test-survival_duration_subgroups.R
- [x] test-table_egt01.R
- [x] test-table_lbt01.R
- [x] test-table_vst01.R

**Comment by Melkiades** [comment]
This comes from [rtables#33](https://github.com/insightsengineering/formatters/issues/33)
