### ISSUE TITLE
new release tag, for OCEAN, by 2023-05-23

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#917]
Blocked by 

- [x] https://github.com/insightsengineering/tern/pull/914
- [x] https://github.com/insightsengineering/tern/pull/912

# TODOs
- [x] Upstream formatters version bump to 0.5.0
- [x] Upstream rtables version bump to 0.6.1
- [x] #920
- [x] Tag the update as a release candidate, v0.8.2-rc1
- [x] Submit v0.8.2-rc1 for validation
- [x] Get v0.8.2-rc1 validated, retag as v0.8.2
- [x] Update downstream package dependencies to (>=0.8.2) in chevron
- [x] Update downstream package dependencies to (>=0.8.2) in citril
